spring:
  datasource:
    url: jdbc:h2:mem:checkout;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2
  spring:
    cache:
      type: caffeine
      cache-names: offers
      caffeine:
        spec: maximumSize=10000,expireAfterWrite=10m
logging.level.org.hibernate.SQL: info
