-- Items
CREATE TABLE items (
  name VARCHAR(255) PRIMARY KEY,
  price_in_minor INT NOT NULL
);

-- Offers
CREATE TABLE offers (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR(255) NOT NULL,
  item VARCHAR(255) NOT NULL,
  metadata CLOB,
  usage_limit INT,
  CONSTRAINT fk_offers_item
    FOREIGN KEY (item) REFERENCES items(name)
);